In [1]:
import tensorflow as tf

In [2]:
import numpy as np
import pandas as pd

# Network with 1 LTSM Cell

In [5]:
LSTM_CELL_SIZE = 4

state = (tf.zeros([1,LSTM_CELL_SIZE]),)*2
state

(<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>)

In [6]:
lstm = tf.keras.layers.LSTM(LSTM_CELL_SIZE, return_sequences=True, return_state=True)
lstm.states = state

print(lstm.states)

(<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>)


## Defining a Sample input for the LTSM Cell

In [7]:
sample_input = tf.constant([[3,2,2,2,2,2]], dtype=tf.float32)

batch_size = 1
sentence_max_length = 1
n_features = 6

new_shape = (batch_size, sentence_max_length, n_features)

inputs = tf.constant(np.reshape(sample_input, new_shape), dtype=tf.float32)

In [8]:
output, final_memory_state, final_carry_state = lstm(inputs)

In [9]:
print('Output : ', tf.shape(output))

print('Memory : ',tf.shape(final_memory_state))

print('Carry state : ',tf.shape(final_carry_state))

Output :  tf.Tensor([1 1 4], shape=(3,), dtype=int32)
Memory :  tf.Tensor([1 4], shape=(2,), dtype=int32)
Carry state :  tf.Tensor([1 4], shape=(2,), dtype=int32)


# LTSM Stack 

Want to have an RNN with stacked LSTM?
Example : 2-layer LSTM

In [10]:
cells = []

In [11]:
LSTM_CELL_SIZE_1 = 4 # 4 hidden nodes
cell1 = tf.keras.layers.LSTMCell(LSTM_CELL_SIZE)
cells.append(cell1)

In [12]:
LSTM_CELL_SIZE_2 = 5 # 5 hidden nodes
cell2 = tf.keras.layers.LSTMCell(LSTM_CELL_SIZE_2)
cells.append(cell2)

In [14]:
# This creates a multi-layer LTSM from an array of single LTSM cells
stacked_lstm = tf.keras.layers.StackedRNNCells(cells)

In [15]:
lstm_layer = tf.keras.layers.RNN(stacked_lstm, return_sequences=True, return_state=True)

In [17]:
#Batch size x time steps x features.
sample_input = [[[1,2,3,4,3,2], \
    [1,2,1,1,1,2],[1,2,2,2,2,2]],\
    [[1,2,3,4,3,2],[3,2,2,1,1,2],\
    [0,0,0,0,3,2]]]

batch_size = 2
time_steps = 3
features = 6
new_shape = (batch_size, time_steps, features)

x = tf.constant(np.reshape(sample_input, new_shape), dtype = tf.float32)

In [18]:
output, final_memory_state, final_carry_state = lstm_layer(x)

In [19]:
print('Output : ', tf.shape(output))

print('Memory : ',tf.shape(final_memory_state))

print('Carry state : ',tf.shape(final_carry_state))

Output :  tf.Tensor([2 3 5], shape=(3,), dtype=int32)
Memory :  tf.Tensor([2 2 4], shape=(3,), dtype=int32)
Carry state :  tf.Tensor([2 2 5], shape=(3,), dtype=int32)
